import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return [{
      id: 1,
      front: 'hello',
      back: 'bird1.png',
      value: 'a',
      isFlipped: false
    }, {
      id: 2,
      front: 'hello',
      back: 'bird1.png',
      value: 'a',
      isFlipped: false
    }, {
      id: 3,
      front: 'hello',
      back: 'bird2.png',
      value: 'b',
      isFlipped: false
    }, {
      id: 4,
      front: 'hello',
      back: 'bird2.png',
      value: 'b',
      isFlipped: false
    }, {
      id: 5,
      front: 'hello',
      back: 'bird3.png',
      value: 'c',
      isFlipped: false
    }, {
      id: 6,
      front: 'hello',
      back: 'bird3.png',
      value: 'c',
      isFlipped: false
    }, {
      id: 7,
      front: 'hello',
      back: 'bird4.png',
      value: 'd',
      isFlipped: false
    }, {
      id: 8,
      front: 'hello',
      back: 'bird4.png',
      value: 'd',
      isFlipped: false
    }, {
      id: 9,
      front: 'hello',
      back: 'bird5.png',
      value: 'e',
      isFlipped: false
    }, {
      id: 10,
      front: 'hello',
      back: 'bird5.png',
      value: 'e',
      isFlipped: false
    }, {
      id: 11,
      front: 'hello',
      back: 'bird6.png',
      value: 'f',
      isFlipped: false
    }, {
      id: 12,
      front: 'hello',
      back: 'bird6.png',
      value: 'f',
      isFlipped: false
    }, {
      id: 13,
      front: 'hello',
      back: 'bird7.png',
      value: 'g',
      isFlipped: false
    }, {
      id: 14,
      front: 'hello',
      back: 'bird7.png',
      value: 'g',
      isFlipped: false
    }, {
      id: 15,
      front: 'hello',
      back: 'bird8.png',
      value: 'h',
      isFlipped: false
    }, {
      id: 16,
      front: 'hello',
      back: 'bird8.png',
      value: 'h',
      isFlipped: false
    }];
  }
});
